all:
	latexmk -pdf 201610response_overseasInvestmentInTechFunds.tex

clean:
	latexmk -c 201610response_overseasInvestmentInTechFunds.tex

squeaky: clean
	rm 201610response_overseasInvestmentInTechFunds.pdf
